version: "3"
services:
  express-app:
    build:
      context: ./express-backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  nuxt-app:
    build:
      context: ./nuxt-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
